### ISSUE TITLE
支持PHP7?

### ISSUE THREAD

**Issue by leopoldwong** [top-think/think-mongo#1]

**Comment by liu21st** [comment]
TP5支持PHP5.4以上版本 所以也支持PHP7

**Comment by leopoldwong** [comment]
PHP7使用MongoDB的方式跟之前的不是不一样吗

**Comment by liu21st** [comment]
think-mongo使用的就是最新的驱动 该驱动支持php7

**Comment by tryfinding** [comment]
手册还没写好，看来用MONGO的不多啊

**Comment by leopoldwong** [comment]
问个问题
PHP7里使用MongoDB\Driver\BulkWrite写入的数据是数组形式的
$document = ['title' => 'one'];
$bulk->insert($document);

PHP里面的数组应该是被解析成json格式了，但是MongoDB里面也存在数组的形式，我怎么在PHP里插入数组类型数据呢
MongoDB Shell中
db.places.insert(
   {
      loc : { type: "Point", coordinates: [ -73.97, 40.77 ] },
   }
)
怎么使用BulkWrite对象写入数组类型的数据呢
