### ISSUE TITLE
升级到 1.5 后是不是不支持这种查询了 $w['map.province'] = '北京';

### ISSUE THREAD

**Issue by Cailiang** [top-think/think-mongo#18]
看您的代码 1.2 的版本是这样的：
` protected function parseKey($key)
    {
        if ('id' == $key && $this->connection->getConfig('pk_convert_id')) {
            $key = '_id';
        }
        return trim($key);
    }`

升级到 1.5 后是这样的
`  protected function parseKey($key)
    {
        if (strpos($key, '.')) {
            list($collection, $key) = explode('.', $key);
        }
        if ('id' == $key && $this->connection->getConfig('pk_convert_id')) {
            $key = '_id';
        }
        return trim($key);
    }`
疑惑的是，为什么要加上这段代码
`if (strpos($key, '.')) {
            list($collection, $key) = explode('.', $key);
        }`
那现在如果需要查询 一个数组中(map)，key(province)为  '北京' 应该怎么写呢 ？

**Comment by liu21st** [comment]
这是为了解决软删除的问题而改的 关于数组的查询 后面再来改进

**Comment by liu21st** [comment]
改进了下 用git最新版本测试下试试

**Comment by Cailiang** [comment]
恩，最新版可以。谢谢！！
