### ISSUE TITLE
使用模型进行无法进行区间查询

### ISSUE THREAD

**Issue by GuoDapeng** [top-think/think-mongo#2]
不好意思我图片传不上来

使用模型
类似下面代码会出现，

                    $bloodPressure = new bloodPressureModel();
                    $bloodPressure = $bloodPressure->where('userId', $id)
                        ->where('time', 'between time', [$start, $end])
                        //->where('time', '>', $start)
                        //->where('time', '<= time', $end)
                        ->select();

注释那两行也是不能用的，我尝试 1569 行输出 $result->getData() 是有结果的。但是只有一条。

[2] ErrorException in Query.php line 1570
array_keys() expects parameter 1 to be array, object given

                // 多表不获取字段信息
                return false;
            } else {
                $tableName = $this->parseSqlTable($tableName);
            }

            $guid = md5($tableName);
            if (!isset($_info[$guid])) {
                $result = $this->table($tableName)->find();
                $fields = array_keys($result);
                $type   = [];
                foreach ($result as $key => $val) {
                    // 记录字段类型
                    $type[$key] = getType($val);
                    if ('_id' == $key) {
                        $pk = $key;
                    }
                }
                if (!isset($pk)) {

Call Stack

    in Query.php line 1570
    at Error::appError(2, 'array_keys() expects...', '/var/www/html/Bodygu...', 1570, ['tableName' => 'bloodPressure', 'fetch' => 'type', '_info' => [], ...])
    at array_keys(object(bloodPressureModel)) in Query.php line 1570
    at Query->getTableInfo('', 'type') in Builder.php line 268
    at Builder->parseDateTime(1468326302, 'time') in Builder.php line 246
    at Builder->parseWhereItem('time', ['between time', [1468326302, 1470918302]]) in Builder.php line 166
    at Builder->parseWhere(['$and' => ['delete_time' => ['=', 0], 'userId' => ['=', '57ab52771d41c8175d01...'], 'time' => ['between time', [1468326302, 1470918302]]]]) in Builder.php line 383
    at Builder->select(['where' => ['$and' => ['delete_time' => ['=', 0], 'userId' => ['=', '57ab52771d41c8175d01...'], 'time' => ['between time', [1468326302, 1470918302]]]], 'table' => 'bloodPressure', 'projection' => [], ...]) in Query.php line 1338
    at Query->select() in Index.php line 928
    at Index->getPatientQuotaTimeRange()
    at ReflectionMethod->invokeArgs(object(Index), []) in App.php line 219
    at App::invokeMethod([object(Index), 'getpatientquotatimer...']) in App.php line 338
    at App::module(['index', 'index', 'getPatientQuotaTimeR...'], ['app_namespace' => 'app', 'app_debug' => true, 'app_trace' => false, ...], null) in App.php line 117
    at App::run() in start.php line 18
    at require('/var/www/html/Bodygu...') in index.php line 17

Exception Datas
Error Context tableName 	bloodPressure
fetch 	type
_info 	[ ]
guid 	00277da3e8439e53fb368907d9e49269
result 	{ "FV": "bloodPressure", "_sv": 0, "_v": 0, "create_at": 1470878024, "delete_time": 0, "diastolic": 2, "shrink": 1, "time": "1470877993", "update_at": 1470878024, "userId": "57ab52771d41c8175d0198d3", "id": "57abd1481d41c81774168753" }
Environment Variables
GET Dataempty
POST Dataempty
Filesempty
Cookies PHPSESSID 	ph3037og45deb0n739hd3g7or0
rock_format 	json
think_var 	zh-cn
Sessionempty
Server/Request Data HTTP_HOST 	192.168.1.31
HTTP_USER_AGENT 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:50.0) Gecko/20100101 Firefox/50.0
HTTP_ACCEPT 	application/json, text/javascript, */*; q=0.01
HTTP_ACCEPT_LANGUAGE 	zh-CN,zh-TW;q=0.8,en-US;q=0.5,en;q=0.3
HTTP_ACCEPT_ENCODING 	gzip, deflate
HTTP_REFERER 	http://192.168.1.31/Bodyguard/public/frontend/htmlDemo/index_demo.html
CONTENT_TYPE 	application/json
HTTP_X_REQUESTED_WITH 	XMLHttpRequest
CONTENT_LENGTH 	217
HTTP_COOKIE 	PHPSESSID=ph3037og45deb0n739hd3g7or0; rock_format=json; think_var=zh-cn
HTTP_CONNECTION 	keep-alive
PATH 	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
SERVER_SIGNATURE 	<address>Apache/2.4.7 (Ubuntu) Server at 192.168.1.31 Port 80</address>
SERVER_SOFTWARE 	Apache/2.4.7 (Ubuntu)
SERVER_NAME 	192.168.1.31
SERVER_ADDR 	192.168.1.31
SERVER_PORT 	80
REMOTE_ADDR 	192.168.1.210
DOCUMENT_ROOT 	/var/www/html
REQUEST_SCHEME 	http
CONTEXT_PREFIX 	
CONTEXT_DOCUMENT_ROOT 	/var/www/html
SERVER_ADMIN 	webmaster@localhost
SCRIPT_FILENAME 	/var/www/html/Bodyguard/public/index.php
REMOTE_PORT 	51988
GATEWAY_INTERFACE 	CGI/1.1
SERVER_PROTOCOL 	HTTP/1.1
REQUEST_METHOD 	POST
QUERY_STRING 	
REQUEST_URI 	/Bodyguard/public/index.php/index/index/getPatientQuotaTimeRange
SCRIPT_NAME 	/Bodyguard/public/index.php
PATH_INFO 	/index/index/getPatientQuotaTimeRange
PATH_TRANSLATED 	/var/www/html/index/index/getPatientQuotaTimeRange
PHP_SELF 	/Bodyguard/public/index.php/index/index/getPatientQuotaTimeRange
REQUEST_TIME_FLOAT 	1470918431.466
REQUEST_TIME 	1470918431
Environment Variablesempty
ThinkPHP Constants APP_PATH 	/var/www/html/Bodyguard/public/../application/
THINK_VERSION 	5.0.0 RC4
THINK_START_TIME 	1470918431.4675
THINK_START_MEM 	239032
EXT 	.php
DS 	/
THINK_PATH 	/var/www/html/Bodyguard/thinkphp/
LIB_PATH 	/var/www/html/Bodyguard/thinkphp/library/
CORE_PATH 	/var/www/html/Bodyguard/thinkphp/library/think/
TRAIT_PATH 	/var/www/html/Bodyguard/thinkphp/library/traits/
ROOT_PATH 	/var/www/html/Bodyguard/public/../
EXTEND_PATH 	/var/www/html/Bodyguard/public/../extend/
VENDOR_PATH 	/var/www/html/Bodyguard/public/../vendor/
RUNTIME_PATH 	/var/www/html/Bodyguard/public/../runtime/
LOG_PATH 	/var/www/html/Bodyguard/public/../runtime/log/
CACHE_PATH 	/var/www/html/Bodyguard/public/../runtime/cache/
TEMP_PATH 	/var/www/html/Bodyguard/public/../runtime/temp/
CONF_PATH 	/var/www/html/Bodyguard/public/../application/
CONF_EXT 	.php
ENV_PREFIX 	PHP_
IS_CLI 	false
IS_WIN 	false

**Comment by GuoDapeng** [comment]
在 Query.php line 1569 行

            $result = $this->table($tableName)->find();
            if(is_object($result)){
                $result = $result->getData();
            }

是否妥当呢？好像是好了

**Comment by liu21st** [comment]
这个问题已经修正过的
