### ISSUE TITLE
建议将'_id'转ObjectID由强制转改为尝试转

### ISSUE THREAD

**Issue by ryanho2009** [top-think/think-mongo#20]
https://github.com/top-think/think-mongo/blob/master/src/Builder.php#L72
```
if ('_id' == $field && !($value instanceof ObjectID)) {
    return new ObjectID($value);
}
```

此行代码里面会强制将_id转为ObjectID

但实际项目中可能存在用字符串做_id的值 （eg: express_session 存在mongodb中就是用字符串的sessionid做的key）

所以建议将此处改为灵活一点，尝试转，不成功也不报错，就用默认值
 
```
if ('_id' == $field && !($value instanceof ObjectID)) {
     try {
         return new ObjectID($value);
     } catch (\Exception $e) {
         return $value;
     }
}
```

初次使用tp5 对整体代码不熟悉，刚好业务中定位到这个问题，不知道现有框架有没有对这种需求好的解决方案。

**Comment by liu21st** [comment]
这里的转换并不影响你的获取啊 是写入转换

**Comment by ryanho2009** [comment]
Query在构建查询语句的时候也调用到Builder的这个方法了

**Comment by liu21st** [comment]
有什么问题么？

**Comment by ryanho2009** [comment]
我要去读取别人存的数据信息，他的数据里面_id就是一个字符串不是ObjectID，在查询的时候我传入了条件['_id'=>'xxxxxx'], TP在构建查询语句的时候执行到上面的语句时就会将这个字符串的_id转为一个ObjectID对象，但是我的这个_id并不是ObjectID，不能转也不应该转, 现在执行到上面的一行代码就异常了。

这种情况虽然是数据里面不规范，但是这种情况确实是存在的，除了改这行代码还有什么好的解决方法吗？

**Comment by liu21st** [comment]
存在一个不是ObjectID对象的_id字段？匪夷所思

**Comment by ryanho2009** [comment]
嗯，这是nodejs里比较知名的express-session+passport写的session数据，他就是用一个字符串的sessionid当做_id存的，我现在用PHP去读他的session数据，除了改这里的代码还有其他办法么？

**Comment by liu21st** [comment]
回头我改进下吧 增加一个设置参数

**Comment by ryanho2009** [comment]
好的，谢了！

**Comment by liu21st** [comment]
你测试下最新的提交看看

**Comment by ryanho2009** [comment]
[0] ThrowableError in Builder.php line 65
致命错误: Cannot access empty property
    
protected function parseValue($value, $field = '')
{
        if ('_id' == $field && 'ObjectID' == $this->$this->connection->getConfig('pk_type') && is_string($value)) {
            return new ObjectID($value);
       }


手误多了个$this ?

但是我去掉一个 在getConfig的时候报未定义数组索引

[8] ErrorException in Connection.php line 188
未定义数组索引: pk_type

**Comment by liu21st** [comment]
嗯 你的Connection类更新没？

**Comment by ryanho2009** [comment]
对，刚才没更新到，现在更新了，还是走到if里面去了，转ObjectID异常，我把值打印出来看看

**Comment by ryanho2009** [comment]
这个是pk_type是要我自己去修改配置是吧？

**Comment by liu21st** [comment]
对的 默认还是ObjectID类型的

**Comment by ryanho2009** [comment]
好了，谢谢！
