### ISSUE TITLE
无法传递查询参数

### ISSUE THREAD

**Issue by Cailiang** [top-think/think-mongo#21]
在 Query.php 中options方法被设置为protected ， 那怎样传递查询参数呢 ？

比如我想返回$cursor，但现在无法调用options方法
$op['fetch_cursor'] = true;
$cursor = Db::name('weather_parsed_events')->options($op)->select();

还有其它方法来传递查询参数吗？请不吝赐教啊

**Comment by liu21st** [comment]
基本上每个参数Query类里面都提供了相应的链式方法的，例如 fetchCursor(true)
