### ISSUE TITLE
使用 Db::name('test') 的方式不会调用 get*Attr 方法

### ISSUE THREAD

**Issue by Cailiang** [top-think/think-mongo#38]
比如有个 updatedAt 字段，并且 model 中 有 getUpdatedAtAttr 方法：

`   /**
     * @param $value 将时间戳自动转换为日期
     * @return bool|string
     */
    public function getUpdatedAtAttr($value)
    {
        return date('Y-m-d H:i:s', $value);
    }

    public function findById2($id, $fields = [])
    {
        return $this->where('_id', 'eq', $id)->find();
    }

    public function findById($id, $fields = [])
    {
       // 使用 该方式 不会调用 getUpdatedAtAttr 方法
        return Db::name('test')->where('_id', 'eq', $id)->find();
    }`

**Comment by Cailiang** [comment]
比如在 Controller 中这样调用，findById 返回的updatedAt（存储的是时间戳）就不会被格式化

`    public function t(){
        $m = new Test();
        $rr = $m->findById2('591c1f1872f1fa01e90a81af');
       // $rr = $m->findById('591c1f1872f1fa01e90a81af');
        return json($rr);
    }`

**Comment by liu21st** [comment]
获取器是模型的功能 Db查询是不会生效的
