### ISSUE TITLE
确定支持mongo，是认真的吗？

### ISSUE THREAD

**Issue by xiaozhuai** [top-think/think-mongo#67]
1. 首先是一个常识性的错误
```diff
-            $host = 'mongodb://' . ($config['username'] ? "{$config['username']}" : '') . ($config['password'] ? ":{$config['password']}@" : '') . $config['hostname'] . ($config['hostport'] ? ":{$config['hostport']}" : '') . '/' . ($config['database'] ? "{$config['database']}" : '');
+            $host = 'mongodb://' . ($config['username'] ? "{$config['username']}" : '') . ($config['password'] ? ":{$config['password']}@" : '') . $config['hostname'] . ($config['hostport'] ? ":{$config['hostport']}" : '');
```
uri上指定的database是用于鉴权的，而不是实际产生数据的数据库。这意味着如果鉴权数据库和实际数据库不是一个的话，不管你怎么配置，就是连不上，气不气？行吧，这个还好，所有人都会犯错，可能是作者疏忽了。我提交了个PR，也算是解决了。但是接下来的问题让人难以理解。

2. 查询构造出的query简直就是奇葩

考虑下面的语句
```php
<?php
Db::name('api_version')
            ->where('platform', 0)
            ->limit(100, 10)
            ->order('api_version', 'desc')
            ->select();
```

调试发现最终构造出的query是这样的...
```
db.api_version.find({"$and":[{"platform":0}]}).sort({"api_version":-1}).limit(10);
```
除了sort，没一个是对的。完全按照官网手册写的代码。
首先查询条件构造的就有问题，哪里来的逻辑与？
其次limit的问题，offset呢？只有limit有什么意义呢？

后面不继续了，顺便说，我不是来喷的，我只是觉得，如果完成度是这样的一个模块，为什么要上线，而且版本号都2.x了，我不知道别人都是怎么用的。作为tp，一个国内知名度这么高的项目，我觉得owner和所有的contributor都要有所担当。

最后，如果我的话让任何人感到不悦，先说声抱歉。

**Comment by liu21st** [comment]
首先表示感谢，有任何问题和反馈官方都欢迎的，本来开源项目就是需要大家一起参与。不过有点需要说明（官方手册也提过） mongo驱动生成的sql仅供参考，并不代表实际的查询（这一点你看过源码就应该会了解），如果查询结果确实存在问题，请及时反馈。

**Comment by mineyang** [comment]
鉴权可以用 params :
```
'database' => [
    'username'      => 'user',
    'password'      => 'pass',
    'params'          => [
        'authSource' => 'admin'
    ],
]
```

**Comment by mineyang** [comment]
那我17年2月份的代码怎么就能用params的？

**Comment by xiaozhuai** [comment]
没说不能用 只是无效 并且这么做本身就是不对的 即使params有效 那也只是配置的优先级问题 也不能认为这就是对的 我强调的是 uri中的数据库是用来鉴权的 仅此而已 这没什么好争论的
见mongodb文档：https://docs.mongodb.com/manual/reference/connection-string/
引用其关于/database的说明
> /database  The name of the database to authenticate

**Comment by xiaozhuai** [comment]
另外 It works 和 It's right 之间是有差距的 此话题到此结束
