### ISSUE TITLE
Log的record()，Debug的remark()，Debug的getRangeTime()都不是static的

### ISSUE THREAD

**Issue by laoguangchao** [top-think/think-mongo#72]
1.Non-static method think\Log::record() should not be called statically
2.Non-static method think\Debug::remark() should not be called statically
3.Non-static method think\Debug::getRangeTime() should not be called statically

**Comment by liu21st** [comment]
请选择合适的版本 5.0版本框架安装1.*版本扩展 5.1版本安装2.*版本扩展
