### ISSUE TITLE
BUG不是一般的多 新版的mongo库。坑死了

### ISSUE THREAD

**Issue by lihao812** [top-think/think-mongo#80]
Connection.php    865行
有_id 主键更新的 直接把_id where条件丢了。这TM弱智吗

`$bulk         = $this->builder->update($query);
//where 条件那里去了？不应该更新下这个么？ 老版本直接 带 option 你这个新版 取得也罢怎么不更新where
$query->setOption('where',['$and'=>$where]);
`

**Comment by liu21st** [comment]
query是一个对象 不需要传入额外的where

**Comment by lihao812** [comment]
知道，问题是 你前面有主键的 _id 的语句，既然已经分析完了，为啥不 setOption('where',$where); 造成更新条件为空，所有数据都更新了。

**Comment by lihao812** [comment]
@liu21st 把 $query 对象打印出来就看到了 where 条件为空，我传值 data里 有主键_id 已经被解析掉了

**Comment by liu21st** [comment]
检查下你是否设置了pk_convert_id 如果设置了 就只能传id 我测试并没发现你说的问题 或者你可以给一段demo代码

**Comment by lihao812** [comment]
很多情况，并不需要转换 _id 成id 而是直接用的 _id 那么就跟 pk_convert_id 没关系了。例子

`D('menu')->update(['_id'=>'5b7a675f430df258bf120476','title'=>'测试菜单']);`

这句语句 正常应该只更新 _id 的值 现在执行完 所有记录都更新了。

**Comment by liu21st** [comment]
问题是你是否设置了pk_convert_id

**Comment by lihao812** [comment]
pk_convert_id  false  没设置

**Comment by liu21st** [comment]
如果你是使用的模型，并且主键不是id的话，需要在模型里面设置pk属性才行
