### ISSUE TITLE
关于mongo排序的兼容问题

### ISSUE THREAD

**Issue by ryanho2009** [top-think/think-mongo#88]
`
   public function order($field, $order = '')
    {
        if (is_array($field)) {
            $this->options['sort'] = $field;
        } else {
            $this->options['sort'][$field] = 'asc' == strtolower($order) ? 1 : -1;
        }
        return $this;
    }

`

排序的时候如果传入的是array 如['rank'=>'desc', 'id'=>'asc'] 会报错，不会转为1/-1, 这种应该框架去兼容呢还是业务逻辑自己取兼容？

**Comment by liu21st** [comment]
调用两次order方法实现先
