### ISSUE TITLE
多个条件组合查询不支持

### ISSUE THREAD

**Issue by hepeichun** [top-think/think-mongo#89]
$map1 = [
        ['name', 'like', 'thinkphp%'],
        ['title', 'like', '%thinkphp'],
    ];
    
$map2 = [
        ['name', 'like', 'kancloud%'],
        ['title', 'like', '%kancloud'],
    ];    
    
Db::table('think_user')
    ->whereOr([ $map1, $map2 ])
    ->select();

**Comment by liu21st** [comment]
最好不要这样用

**Comment by hepeichun** [comment]
> 最好不要这样用

如果不这样使用，我需要查出两次数据，然后做排序，并且不能保证时间顺序下面两次获取的数据是否完整。

**Comment by liu21st** [comment]
where(闭包)->whereOr(闭包) 就可以了
