### ISSUE TITLE
tp6 调用think-mongo 报错

### ISSUE THREAD

**Issue by hbh112233abc** [top-think/think-mongo#95]
Argument 1 passed to think\Db::newQuery() must be an instance of think\db\Connection or null, instance of think\db\connector\Mongo given ...

发现`think\db\connector\Mongo`需要继承 `think\db\Connection`
修改`think\db\connector\Mongo`继承 `think\db\Connection`后以上问题解决

然后接下来find报错
```
Declaration of think\db\connector\Mongo::find(think\db\Mongo $query): array must be compatible with think\db\Connection::find(think\db\Query $query): array
```
这个报错不知道如果修改,请官方修复,谢谢

**Comment by liu21st** [comment]
你用的是最新的开发版测试的么？

**Comment by hbh112233abc** [comment]
> 你用的是最新的开发版测试的么？

是的 tp6是最新开发版,think-mongo也是最新版本,都是composer 安装更新到最新的

**Comment by hbh112233abc** [comment]
> 你用的是最新的开发版测试的么？

今天用了老大昨天更新的以上的问题没有了,不过出现新的问题
Db::connect('mongo')->table('tableName')...
在connect之后connection有切为mongo连接,不过在table的时候连接类又切回默认的mysql连接了

**Comment by liu21st** [comment]
@hbh112233abc 你说的问题修正了 是框架的问题
